output.sql

DESC CUSTOMERS;
SQL result

Host: 127.0.0.1
Database: broadcom
Generation Time: Sep 04, 2021 at 09:13 PM
Generated by: phpMyAdmin 4.4.14 / MySQL 5.6.26
SQL query: SELECT * FROM `customers` LIMIT 0, 25 ;
Rows: 10
ID 	NAME 	AGE 	ADDRESS1 	ADDRESS2 	SALARY
1 	Ramesh 	32 	Ahmedabad 	India 	2000.00
2 	Khilan 	25 	Delhi 	India 	1500.00
3 	kaushik 	23 	Phoenix 	Arizona 	2000.00
4 	Chaitali 	25 	Mumbai 	India 	6500.00
5 	Hardik 	27 	Bhopal 	India 	8500.00
6 	Komal 	22 	Cleveland 	OHIO 	4500.00
7 	Thorsen 	60 	Chicago 	Illinois 	8800.00
8 	Smith 	15 	Abbotsford 	Wisconsin 	1500.00
9 	Fricks 	85 	Tomah 	Wisconsin 	5500.00
10 	Dorman 	24 	Wausau 	Wisconsin 	9500.00

SELECT ID, NAME, SALARY 
FROM CUSTOMERS
WHERE SALARY > 2000;

SQL result

Host: 127.0.0.1
Database: broadcom
Generation Time: Sep 04, 2021 at 09:15 PM
Generated by: phpMyAdmin 4.4.14 / MySQL 5.6.26
SQL query: SELECT ID, NAME, SALARY FROM CUSTOMERS WHERE SALARY > 2000 LIMIT 0, 25 ;
Rows: 6
ID 	NAME 	SALARY
4 	Chaitali 	6500.00
5 	Hardik 	8500.00
6 	Komal 	4500.00
7 	Thorsen 	8800.00
9 	Fricks 	5500.00
10 	Dorman 	9500.00

CREATE VIEW `my user view` AS SELECT `name`,`age` FROM `CUSTOMERS`;

SQL result

Host: 127.0.0.1
Database: broadcom
Generation Time: Sep 04, 2021 at 09:18 PM
Generated by: phpMyAdmin 4.4.14 / MySQL 5.6.26
SQL query: SELECT * FROM `my user view` LIMIT 0, 25 ;
Rows: 10
name 	age
Ramesh 	32
Khilan 	25
kaushik 	23
Chaitali 	25
Hardik 	27
Komal 	22
Thorsen 	60
Smith 	15
Fricks 	85
Dorman 	24

SQL result

Host: 127.0.0.1
Database: broadcom
Generation Time: Sep 04, 2021 at 09:19 PM
Generated by: phpMyAdmin 4.4.14 / MySQL 5.6.26
SQL query: Select * from CUSTOMERS order by Name LIMIT 0, 25 ;
Rows: 10
ID 	NAME 	AGE 	ADDRESS1 	ADDRESS2 	SALARY
4 	Chaitali 	25 	Mumbai 	India 	6500.00
10 	Dorman 	24 	Wausau 	Wisconsin 	9500.00
9 	Fricks 	85 	Tomah 	Wisconsin 	5500.00
5 	Hardik 	27 	Bhopal 	India 	8500.00
3 	kaushik 	23 	Phoenix 	Arizona 	2000.00
2 	Khilan 	25 	Delhi 	India 	1500.00
6 	Komal 	22 	Cleveland 	OHIO 	4500.00
1 	Ramesh 	32 	Ahmedabad 	India 	2000.00
8 	Smith 	15 	Abbotsford 	Wisconsin 	1500.00
7 	Thorsen 	60 	Chicago 	Illinois 	8800.00

SQL result

Host: 127.0.0.1
Database: broadcom
Generation Time: Sep 04, 2021 at 09:22 PM
Generated by: phpMyAdmin 4.4.14 / MySQL 5.6.26
SQL query: SELECT NAME,age FROM CUSTOMERS WHERE age>0 order by age LIMIT 0, 25 ;
Rows: 10
Current selection does not contain a unique column. Grid edit, checkbox, Edit, Copy and Delete features are not available.
NAME 	age
Smith 	15
Komal 	22
kaushik 	23
Dorman 	24
Chaitali 	25
Khilan 	25
Hardik 	27
Ramesh 	32
Thorsen 	60
Fricks 	85

